### PR TITLE
Diff drive brake

### PR DESCRIPTION
**Pull request by dandedrick**
This prevents the wheels in the simulation from drifting around. We only need the gazebo_plugin package so I've added CATKIN_IGNORE files to all the other packages. I've also created an upstream PR for my changes here: https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1230

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1)

### CODE REVIEW

**Comment by dandedrick** [comment]
This needs some rework for upsteam to support gazebo9.

**Comment by dandedrick** [comment]
I've updated this to support gazebo 9 so I think this should now be passing the upstream CI checks.

**Review by bobhenz-jabil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @dandedrick)

___
*[gazebo_plugins/src/gazebo_ros_diff_drive.cpp, line 131 at r1](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1#-MTv0Fn10P0qQWQ-g56y:-MTv0Fn10P0qQWQ-g56z:bk8jk2o) ([raw file](https://github.com/badgertechnologies/gazebo_ros_pkgs/blob/aca10e4cc5efb4808adf3ecea710bb8f2dc8cb6a/gazebo_plugins/src/gazebo_ros_diff_drive.cpp#L131)):*
> ```cpp
>       brakes_applied_[RIGHT] = false;
>       updateBrakeState(RIGHT, true);
>     }
> ```

This is a little confusing to me. I think it would make more sense if the `brakes_applied_[LEFT/RIGHT]` were initialized outside of the "if". To me, they should still be initialized even if enable_braking_ is not currently "true". I know there's no way for enable_braking_ to change, but I still feel more comfortable with initializing all the things to a default regardless of use. But if you don't like that then at least _before_ the calls to `updateBrakeState()` the reason being, that everywhere else in the code that's how it's done. First the brakes_applied_ is put into the correct state, _then_ `updateBrakeState()` is called.

**Review by bobhenz-jabil — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @dandedrick)

**Review by bobhenz-jabil — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @dandedrick)

**Review by dandedrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @bobhenz-jabil)

___
*[gazebo_plugins/src/gazebo_ros_diff_drive.cpp, line 131 at r1](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1#-MTv0Fn10P0qQWQ-g56y:-MTv38CC09OlbhuCi55v:b9qxpz9) ([raw file](https://github.com/badgertechnologies/gazebo_ros_pkgs/blob/aca10e4cc5efb4808adf3ecea710bb8f2dc8cb6a/gazebo_plugins/src/gazebo_ros_diff_drive.cpp#L131)):*
<details><summary><i>Previously, bobhenz-jabil (Bob Henz) wrote…</i></summary><blockquote>

This is a little confusing to me. I think it would make more sense if the `brakes_applied_[LEFT/RIGHT]` were initialized outside of the "if". To me, they should still be initialized even if enable_braking_ is not currently "true". I know there's no way for enable_braking_ to change, but I still feel more comfortable with initializing all the things to a default regardless of use. But if you don't like that then at least _before_ the calls to `updateBrakeState()` the reason being, that everywhere else in the code that's how it's done. First the brakes_applied_ is put into the correct state, _then_ `updateBrakeState()` is called.
</blockquote></details>

So I can move the initializations outside of the if. It wouldn't make sense to set this elsewhere because they pass the state they want as an argument to the function. the function then only does something if the passed value doesn't match the current value. Setting them before calling would mean that it would never do anything.

**Review by bobhenz-jabil — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/gazebo_ros_pkgs/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dandedrick)

**Pull request merged**
